wheel_radius: 0.09
wheel_thickness: 0.02
track_width: 0.23
wheel_base: 0.19
base_link_length: 0.4
lidar_thickness: 0.02
base_link_height: 0.1
lidar_radius: 0.035
base_lidar_distance_x: 0.1
base_caster_distance: 0.15

