wheel_radius: 0.078
wheel_thickness: 0.03
track_width: 0.21920
wheel_base: 0.187
base_link_length: 0.4
lidar_thickness: 0.0194
base_link_height: 0.1033
lidar_radius: 0.03461
base_lidar_distance_x: 0.1
base_caster_distance: 0.15

